version: '3.4'

services:
  crkn-digirati-editor:
    image: crkn-digirati-editor
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000